/** Seed content for the in-memory demo backend. */

import type { Business, Shift, WorkerProfile } from './types';

export const SEED_BUSINESSES: Business[] = [
  {
    id: 'biz_bluebottle',
    companyName: 'Blue Harbor Coffee',
    category: 'Café',
    city: 'Oakland, CA',
    about: 'Neighborhood specialty coffee bar with two locations near Lake Merritt.',
    contactName: 'Dana Reyes',
  },
  {
    id: 'biz_tacos',
    companyName: 'El Farolito Cocina',
    category: 'Restaurant',
    city: 'Oakland, CA',
    about: 'Busy family taqueria. Fast-paced kitchen, friendly crew.',
    contactName: 'Marco Salinas',
  },
  {
    id: 'biz_warehouse',
    companyName: 'Bayside Fulfillment',
    category: 'Warehouse',
    city: 'Emeryville, CA',
    about: 'Regional e-commerce fulfillment center. Day and swing shifts.',
    contactName: 'Priya Nair',
  },
  {
    id: 'biz_grocer',
    companyName: 'Rockridge Market',
    category: 'Retail',
    city: 'Oakland, CA',
    about: 'Independent grocer and deli. We hire for nights and weekends.',
    contactName: 'Sam Okafor',
  },
  {
    id: 'biz_events',
    companyName: 'Lakeside Events Co.',
    category: 'Hospitality',
    city: 'Oakland, CA',
    about: 'Catering and event staffing for weddings and corporate events.',
    contactName: 'Tessa Brandt',
  },
];

const soon = (offsetDays: number) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().slice(0, 10);
};

/** Demo shifts all use the original swipe-and-match flow. */
const STANDARD_SHIFTS: Omit<Shift, 'fillMode'>[] = [
  {
    id: 'shift_barista_sat',
    businessId: 'biz_bluebottle',
    title: 'Weekend Barista',
    role: 'Barista',
    payRate: 22,
    payType: 'hour',
    date: soon(2),
    startTime: '07:00',
    endTime: '15:00',
    location: 'Lakeshore Ave, Oakland',
    description:
      'Cover our Saturday morning rush. Pull shots, dial in espresso, and keep the line moving with a smile.',
    requirements: ['Espresso experience', 'Food handler card', 'Weekend availability'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shift_linecook',
    businessId: 'biz_tacos',
    title: 'Line Cook — Dinner',
    role: 'Line Cook',
    payRate: 24,
    payType: 'hour',
    date: soon(1),
    startTime: '16:00',
    endTime: '23:00',
    location: 'International Blvd, Oakland',
    description: 'Grill and plancha station during dinner service. High volume, great crew.',
    requirements: ['1+ yr line experience', 'Can stand for 7 hrs', 'ServSafe a plus'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shift_picker',
    businessId: 'biz_warehouse',
    title: 'Warehouse Picker/Packer',
    role: 'Warehouse Associate',
    payRate: 21,
    payType: 'hour',
    date: soon(1),
    startTime: '06:00',
    endTime: '14:30',
    location: 'Hollis St, Emeryville',
    description: 'Pick, pack, and label outbound orders. Lift up to 40 lbs. Steel-toe boots required.',
    requirements: ['Lift 40 lbs', 'Steel-toe boots', 'Reliable transport'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shift_cashier',
    businessId: 'biz_grocer',
    title: 'Evening Cashier',
    role: 'Cashier',
    payRate: 20,
    payType: 'hour',
    date: soon(3),
    startTime: '15:00',
    endTime: '21:00',
    location: 'College Ave, Oakland',
    description: 'Run the front register during evening hours and help bag and restock at close.',
    requirements: ['Cash handling', 'Friendly', 'Evenings'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shift_server',
    businessId: 'biz_events',
    title: 'Banquet Server — Wedding',
    role: 'Server',
    payRate: 28,
    payType: 'hour',
    date: soon(5),
    startTime: '15:30',
    endTime: '23:30',
    location: 'Lake Merritt Pavilion, Oakland',
    description: 'Plated dinner service for a 120-guest wedding. Black slacks and white shirt required.',
    requirements: ['Banquet experience', 'Black/white attire', 'Tray service'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'shift_barback',
    businessId: 'biz_events',
    title: 'Event Barback',
    role: 'Barback',
    payRate: 23,
    payType: 'hour',
    date: soon(5),
    startTime: '16:00',
    endTime: '23:59',
    location: 'Lake Merritt Pavilion, Oakland',
    description: 'Keep the bar stocked with ice, glassware, and garnishes during a busy reception.',
    requirements: ['21+', 'Can lift kegs', 'Fast on your feet'],
    status: 'open',
    createdAt: new Date().toISOString(),
  },
];

export const SEED_SHIFTS: Shift[] = STANDARD_SHIFTS.map((s) => ({
  ...s,
  fillMode: 'standard',
}));

/**
 * Demo worker profiles. These also seed the business deck: each is treated as
 * having already "liked" the matching shift, so a freshly-onboarded business
 * immediately has applicants to swipe through.
 */
export const SEED_WORKERS: (WorkerProfile & { likedShiftIds: string[] })[] = [
  {
    id: 'wk_jordan',
    fullName: 'Jordan Avery',
    headline: 'Barista · Espresso nerd',
    bio: 'Three years behind the bar at two specialty shops. Latte art, dialing in, and a fast, calm rush.',
    city: 'Oakland, CA',
    skills: ['Espresso', 'Latte art', 'POS', 'Customer service'],
    yearsExperience: 3,
    desiredRate: 22,
    availability: ['Weekends', 'Mornings'],
    likedShiftIds: ['shift_barista_sat'],
  },
  {
    id: 'wk_maria',
    fullName: 'María González',
    headline: 'Line cook · Grill & plancha',
    bio: 'Fast hands on a hot line. Comfortable in high-volume taqueria and diner kitchens.',
    city: 'Oakland, CA',
    skills: ['Grill', 'Prep', 'Plancha', 'ServSafe'],
    yearsExperience: 5,
    desiredRate: 25,
    availability: ['Evenings', 'Weekends'],
    likedShiftIds: ['shift_linecook'],
  },
  {
    id: 'wk_devon',
    fullName: 'Devon Clarke',
    headline: 'Warehouse & logistics',
    bio: 'Forklift certified, dependable, and quick on the pick line. Always on time.',
    city: 'Emeryville, CA',
    skills: ['Picking', 'Packing', 'Forklift', 'Inventory'],
    yearsExperience: 4,
    desiredRate: 21,
    availability: ['Early mornings', 'Weekdays'],
    likedShiftIds: ['shift_picker'],
  },
  {
    id: 'wk_aisha',
    fullName: 'Aisha Bello',
    headline: 'Server · Banquets & fine dining',
    bio: 'Polished banquet and event server. Tray service, wine basics, and great with guests.',
    city: 'Oakland, CA',
    skills: ['Tray service', 'Fine dining', 'Wine', 'Events'],
    yearsExperience: 6,
    desiredRate: 28,
    availability: ['Weekends', 'Evenings'],
    likedShiftIds: ['shift_server', 'shift_barback'],
  },
  {
    id: 'wk_tyler',
    fullName: 'Tyler Nguyen',
    headline: 'Retail & cash handling',
    bio: 'Friendly, reliable cashier with deli and restock experience. Open evenings and weekends.',
    city: 'Oakland, CA',
    skills: ['Cash handling', 'Restocking', 'Deli', 'Customer service'],
    yearsExperience: 2,
    desiredRate: 20,
    availability: ['Evenings', 'Weekends'],
    likedShiftIds: ['shift_cashier'],
  },
];
